### ISSUE TITLE
Popup Notifications on Web Interface

### ISSUE THREAD

**Issue by jslay88** [jslay88/OctoPrint-Dropbox-Timelapse#1]
* Add `Uploading Timelapse to Dropbox...` and `Timelapse Uploaded to Dropbox!` popup notifications, similar to the `Rendering Timelapse...` and `Timelapse Render Finished.` popups that already exist.

**Comment by jslay88** [comment]
This could help close #6

**Comment by FormerLurker** [comment]
I added these popups to the [octolapse-hooks-v2](https://github.com/jslay88/OctoPrint-Dropbox-Timelapse/tree/octolapse-hooks-v2) branch.  There is a popup for upload start, upload success, upload-failed, and delete-failed.  Might need better messages, but they are decent.
