### ISSUE TITLE
Version 0.1.3 still thinks it's 0.1.2

### ISSUE THREAD

**Issue by jo2y** [jslay88/OctoPrint-Dropbox-Timelapse#11]
I repeatedly get a notice from octoprint to update this plugin to 0.1.3. When I accept, the update the dialog reports that 0.1.2 is installed. It looks like changing https://github.com/jslay88/OctoPrint-Dropbox-Timelapse/blob/master/setup.py#L17 was missed.

**Comment by AnduriI** [comment]
I can confirm this, after updating it still thinks to be 0.1.2.

**Comment by xh3dx** [comment]
Same. Update to 0.1.3. After update and when watching the install script, it appears to be re-installing 0.1.2

**Comment by jslay88** [comment]
Waiting for code review and merge. Staying on 0.1.3, so you'll get one more notification once the actual version bump in the file happens. #13

**Comment by jslay88** [comment]
Didn't mean to close until the release happens. Sorry.

**Comment by jslay88** [comment]
Version has been bumped correctly this time. You should only get 1 more notification for 0.1.3, install that, and you should be good.
