### ISSUE TITLE
python 3.6 support

### ISSUE THREAD

**Issue by Nickjallday** [jslay88/OctoPrint-Dropbox-Timelapse#14]
Ocotoprint will no longer support previous versions of python in the near future, it would be awesome if this plugin could get updated to be compatible with python 3.6.

**Comment by FormerLurker** [comment]
I will take a look next time I'm running python 3 tests.  I didn't see anything last time I looked at the code that definitely would NOT be supported, but I didn't scrutinize at all.  Thanks for the heads up (again)!

**Comment by jslay88** [comment]
What I had is already 2/3 compliant. Just needs compat set.
