### ISSUE TITLE
Post Install Requires Reload Only - Settings Doesn't Show Up Until Restart

### ISSUE THREAD

**Issue by jakest** [jslay88/OctoPrint-Dropbox-Timelapse#4]
After installing the plugin via the OctoPrint web interface, the UI asks to reload the UI to display settings. However, a reload doesn't show the new settings page. You have to restart OctoPrint to see it.

The plugin should restart Octoprint instead of reloading it.

**Comment by jslay88** [comment]
Ahh, thanks. Will push new version shortly

**Comment by jslay88** [comment]
Fixed. Thanks for the report.
