### ISSUE TITLE
Doesn't seem to work with OctoLapse

### ISSUE THREAD

**Issue by snowe2010** [jslay88/OctoPrint-Dropbox-Timelapse#7]
Octolapse saves to the Timelapses folder, but they are not uploaded to dropbox.

**Comment by 3dhmpf** [comment]
Same here... 😔

**Comment by SamKemp** [comment]
@snowe2010 and @3dhmpf 
I have made a fork of this plugin that should work with OctoLapse (depending on your version)

Tested on OctoPrint 1.4.0rc5 and Octolapse 0.4.0rc1.dev3
Feel free to open an issue/comment over there if you have any problems

[https://github.com/SamKemp/OctoPrint-Dropbox-Octolapse](https://github.com/SamKemp/OctoPrint-Dropbox-Octolapse)

**Comment by 3dhmpf** [comment]
Thx! Will test it!👍

**Comment by jslay88** [comment]
> @snowe2010 and @3dhmpf
> I have made a fork of this plugin that should work with OctoLapse (depending on your version)
> 
> Tested on OctoPrint 1.4.0rc5 and Octolapse 0.4.0rc1.dev3
> Feel free to open an issue/comment over there if you have any problems
> 
> https://github.com/SamKemp/OctoPrint-Dropbox-Octolapse

If your tests work well with the main GA builds of OctoPrint, feel free to add an event if statement and open a PR. Makes more sense to keep it all in one plugin that hooks things accordingly, no?

Also, I haven't been using my printer for some time, hence the lack of additional features added. I'll see if I can't dust her off and provide some additional updates here as well if no PR.

**Comment by FormerLurker** [comment]
Why not change the checked in code from

```
def on_event(self, event, payload):
        from octoprint.events import Events
        if event == Events.PLUGIN_OCTOLAPSE_MOVIE_DONE:
            self.upload_timelapse(payload)
```
to
```
def on_event(self, event, payload):
        from octoprint.events import Events
        if event == Events.PLUGIN_OCTOLAPSE_MOVIE_DONE or event == Events.MOVIE_DONE:
            self.upload_timelapse(payload)
```
That way you will get both Octolapse AND stock timelapse uploads.

**Comment by jslay88** [comment]
> Why not change the checked in code from
> 
> ```
> def on_event(self, event, payload):
>         from octoprint.events import Events
>         if event == Events.PLUGIN_OCTOLAPSE_MOVIE_DONE:
>             self.upload_timelapse(payload)
> ```
> 
> to
> 
> ```
> def on_event(self, event, payload):
>         from octoprint.events import Events
>         if event == Events.PLUGIN_OCTOLAPSE_MOVIE_DONE or event == Events.MOVIE_DONE:
>             self.upload_timelapse(payload)
> ```
> 
> That way you will get both Octolapse AND stock timelapse uploads.

See previous comment and PR above yours.

**Comment by FormerLurker** [comment]
@jslay88, thanks, I didn't see the pull request.  I was looking at the fork.  I will comment on the PR and will add my 2 cents.

**Comment by jslay88** [comment]
@snowe2010 @3dhmpf Working on a solution, but this has opened up a can of worms that stems all the way down into the core of OctoPrint and has sparked some discussions. See the following links.

Initially sparked a PR here: https://github.com/jslay88/OctoPrint-Dropbox-Timelapse/pull/9
Which then lead to another discovery and discussion here: https://github.com/FormerLurker/Octolapse/pull/453
Which has opened a FR here: https://github.com/foosel/OctoPrint/issues/3458
Which has also sparked discussions and ideas around Event/Event System restructuring: https://github.com/FormerLurker/Octolapse/pull/453#issuecomment-589521341_

So, it may be a bit if you want to manually install the package provided by @SamKemp to hold you over until a final solution is found and developed. This issue will remain open as the final place to close it all out.

**Comment by FormerLurker** [comment]
So, I think I have a pretty good soution.  I pushed a new branch at [octolapse-hooks-v2](https://github.com/jslay88/OctoPrint-Dropbox-Timelapse/tree/octolapse-hooks-v2), that supports any event you want to define.  MovieDone is added by default, no matter what the settings are, though this could change.  Here is the default *additional_upload_events* settings: 
```
additional_upload_events=[
    {
        'event_name': 'PLUGIN_OCTOLAPSE_MOVIE_DONE',
        'payload_path_key': 'movie'
    },
    {
        'event_name': 'PLUGIN_OCTOLAPSE_SNAPSHOT_ARCHIVE_DONE',
        'payload_path_key': 'archive'
    }
]
```
For fun I thought I'd generalize the solution by adding a *payload_path_key* parameter that is used to extract the path from the payload dictionary later.  This makes it pretty easy to add any event that contains a file path.  To test this I added a new event to Octolapse that fires after a snapshot image archive is created also added a new event to Octolapse that can be used for uploading snapshot image zip files.  This can be found in the most recent devel branch of Octolapse.

Events are stored as a dict, where the event name string is the key, and the payload path attribute is the value.  Checking for events is pretty fast, since it's just a key lookup.  The event dict is reloaded any time settings are saved, but I did NOT add settings to the UI yet.  It could be done via config.yaml, though.

One additional thing to note, previously the plugin used the payload parameter *move_basename* to get the file name, but I just used os.path.basename to remove the reliance on another payload value, reducing the settings necessary to generalize event description.

I did test this on both my windows machine and my Pi.  Please let me know what you think.

**Comment by FormerLurker** [comment]
I added UI settings for the additional upload events:

![image](https://user-images.githubusercontent.com/33363128/75084873-fce17000-54e8-11ea-8aa4-4192d7b6eab9.png)

Might need a bit of cleanup, and maybe some validation, but it seems to work ok.

**Comment by snowe2010** [comment]
Whew, that is a very large can of worms that was opened. I am in no rush for this support, so I will just keep watching this thread. Thanks for the hard work! It's very appreciated!

**Comment by FormerLurker** [comment]
@snowe2010, are you willing to test the version I uploaded?  You can do so from the plugin manager by clicking *get more...* and using this url in the *from url...* box:  https://github.com/jslay88/OctoPrint-Dropbox-Timelapse/archive/octolapse-hooks-v2.zip

I also added popup notifications, so let me know if those work as well please.  Thanks!

**Comment by TWIISTED-STUDIOS** [comment]
I have tested this out for the past half hour and all the log files are saying are no Dropbox API token when I have given it the API key and also changed API keys to see if that was the issue but it's claiming the API key wasn't found. 

![image](https://user-images.githubusercontent.com/20824886/75106214-dff48c00-5611-11ea-8b87-afbe219361cc.png)

**Comment by FormerLurker** [comment]
@TWIISTED-SHOPS, thank you for trying it out!  The testing is most appreciated and critical for finding/fixing issues like these.

Can you edit your config.yaml file and see what settings exist for dropbox_timelapse?  It should look something like this:

```
dropbox_timelapse:
    api_token: HUGE_API_STRING_HERE
```

In the meanwhile, I will uninstall and reinstall and see if I can replicate the issue.

**Comment by FormerLurker** [comment]
Ok, I think I found the culprit.  Not fixed yet, but this log entry looks promising:

```
2020-02-23 19:20:02,663 - octoprint.server.util.flask.collect_plugin_assets - WARNING - Plugin dropbox_timelapse is referring to non existing js asset js/settings.js
```

It looks like I goofed the setup.py somewhere along the way.  I need to figure out a good way to debug setup, speaking of that...  I will push an update as soon as I get it straightened out.

**Comment by TWIISTED-STUDIOS** [comment]
interesting inside the config.yaml file listed in the components where all the plugins are is no sign of dropbox_timlapse and then there is no Dropbox_timelapse api_token either, however sams plugin that he made as a fork is showing up but it is disabled and shows as disabled.

**Comment by FormerLurker** [comment]
Wow, is my face red, lol!  So, the reason it worked for me was that I had previously copied the files manually for quick testing,.  However, somehow I forgot to add settings.js to the repository, and neglected to include the static folder in the manifest (though that's probably not technically required).

Anyway, I reinstalled and changed the API key, and saving it DOES now seem to add the dropbox_timelapse entry to the config.yaml file.  Also, the default settings are now showing up in the settings page initially, so it looks like it's time to try again by installing from the same url.

**Comment by TWIISTED-STUDIOS** [comment]
Will give it another try then and see what happens this time, and then update you when I have found out. 

Update all seems to be working fine the files get uploaded to dropbox and the toast notifications also pop up on the screen telling you it was successful in uploading.

**Comment by FormerLurker** [comment]
Excellent.  I will wait for OP (@snowe2010) to try it out before submitting a pull request.

**Comment by snowe2010** [comment]
@FormerLurker sure thing! I haven't had anything I've been in a rush to print lately and I've also been quite busy. I'll try to test as soon as possible, but probably won't be able to test until tomorrow night.

**Comment by FormerLurker** [comment]
@snowe2010, thanks!  There is no particular rush, except that I'm excited to submit a pull request if it all works as expected :)  Tomorrow night is more than fine.  FYI, if you are using Octolapse v0.4.0rc1.dev3 or above, you can enable snapshot archiving within your rendering profile:

![image](https://user-images.githubusercontent.com/33363128/75472462-28d17b00-5959-11ea-8e65-da52771c664f.png)

These zip archives of your images should be uploaded as well, along with any timelapses that are produced as long as you are using the default Dropbox Timelapse plugin.

**Comment by snowe2010** [comment]
@FormerLurker so I should see the items being uploaded into either the `movie` or `archive` folders? I'm not, though I can see them in the `Apps>Tyler's OctoLapse`. Actually I can see everything there. I didn't even realize it was a folder... It has a weird puzzle piece icon.

**Comment by 3dhmpf** [comment]
@FormerLurker your plugin is working fine 👍🏼
Tested on Octoprint 1.4.0rc3 and octolapse v0.4.0rc1.dev3

**Comment by FormerLurker** [comment]
@snowe2010, sorry for the late response (been out of town). 

> so I should see the items being uploaded into either the movie or archive folders

I think it will all go into the root of the app folder.  Should archives and movies be separated?  It would be possible to add some kind of subfolder specifier I suppose (but not for this PR).

> Actually I can see everything there.

Do you mean that they are being uploaded correctly?

**Comment by snowe2010** [comment]
@FormerLurker I'm seeing stuff be uploaded, yes! I think I might just misunderstand the purpose of the plugin, no worries!

**Comment by FormerLurker** [comment]
@snowe2010, thanks!  I'm going to submit a pull request then.
